import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { apiFetch, type ApiResult } from '../../api/client'
import { useAuth } from '../../auth/AuthContext'
import type { Article } from '../../types'

type Form={title:string;slug:string;excerpt:string;content:string;cover_image_url:string;status:'draft'|'published'}
const empty:Form={title:'',slug:'',excerpt:'',content:'',cover_image_url:'',status:'draft'}
export function ArticlesAdminPage(){const {accessToken,can}=useAuth();const qc=useQueryClient();const [editing,setEditing]=useState<Article|null>(null);const [form,setForm]=useState<Form>(empty);const q=useQuery({queryKey:['admin-articles'],queryFn:()=>apiFetch<ApiResult<Article[]>>('/admin/articles',{},accessToken),enabled:!!accessToken});const save=useMutation({mutationFn:()=>editing?apiFetch(`/admin/articles/${editing.id}`,{method:'PUT',body:JSON.stringify(form)},accessToken):apiFetch('/admin/articles',{method:'POST',body:JSON.stringify(form)},accessToken),onSuccess:()=>{setEditing(null);setForm(empty);void qc.invalidateQueries({queryKey:['admin-articles']})}});const del=useMutation({mutationFn:(id:string)=>apiFetch(`/admin/articles/${id}`,{method:'DELETE'},accessToken),onSuccess:()=>void qc.invalidateQueries({queryKey:['admin-articles']})});return <div className="admin-page"><div className="admin-title"><div><span className="eyebrow">CMS</span><h1>Artikel</h1></div></div>{can('articles.write')&&<form className="panel form-grid" onSubmit={e=>{e.preventDefault();save.mutate()}}><h2>{editing?'Edit Artikel':'Artikel Baru'}</h2><label>Judul<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value,slug:editing?form.slug:e.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label className="span-2">Excerpt<input value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><label className="span-2">Isi artikel<textarea rows={10} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><label>Cover URL<input value={form.cover_image_url} onChange={e=>setForm({...form,cover_image_url:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as 'draft'|'published'})}><option value="draft">Draft</option><option value="published">Published</option></select></label><div className="form-actions span-2"><button className="btn">Simpan</button>{editing&&<button className="btn btn-secondary" type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Batal</button>}</div></form>}<div className="table-wrap"><table><thead><tr><th>Judul</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{q.data?.data.map(a=><tr key={a.id}><td><strong>{a.title}</strong><small>{a.slug}</small></td><td>{a.status}</td><td className="actions">{can('articles.write')&&<><button onClick={()=>{setEditing(a);setForm({title:a.title,slug:a.slug,excerpt:a.excerpt,content:a.content||'',cover_image_url:a.cover_image_url,status:a.status||'draft'})}}>Edit</button><button className="danger-link" onClick={()=>confirm('Hapus artikel?')&&del.mutate(a.id)}>Hapus</button></>}</td></tr>)}</tbody></table></div></div>}
